// source: common.proto
// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.cloud.pass.grpc.common;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommonRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommonRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string kubeconfig = 1;</code>
     */
    java.lang.String getKubeconfig();
    /**
     * <code>string kubeconfig = 1;</code>
     */
    com.google.protobuf.ByteString
        getKubeconfigBytes();
  }
  /**
   * Protobuf type {@code CommonRequest}
   */
  public  static final class CommonRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommonRequest)
      CommonRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommonRequest.newBuilder() to construct.
    private CommonRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommonRequest() {
      kubeconfig_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommonRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              kubeconfig_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloud.pass.grpc.common.Common.internal_static_CommonRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloud.pass.grpc.common.Common.internal_static_CommonRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloud.pass.grpc.common.Common.CommonRequest.class, com.cloud.pass.grpc.common.Common.CommonRequest.Builder.class);
    }

    public static final int KUBECONFIG_FIELD_NUMBER = 1;
    private volatile java.lang.Object kubeconfig_;
    /**
     * <code>string kubeconfig = 1;</code>
     */
    public java.lang.String getKubeconfig() {
      java.lang.Object ref = kubeconfig_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kubeconfig_ = s;
        return s;
      }
    }
    /**
     * <code>string kubeconfig = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKubeconfigBytes() {
      java.lang.Object ref = kubeconfig_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kubeconfig_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKubeconfigBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, kubeconfig_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKubeconfigBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, kubeconfig_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cloud.pass.grpc.common.Common.CommonRequest)) {
        return super.equals(obj);
      }
      com.cloud.pass.grpc.common.Common.CommonRequest other = (com.cloud.pass.grpc.common.Common.CommonRequest) obj;

      boolean result = true;
      result = result && getKubeconfig()
          .equals(other.getKubeconfig());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KUBECONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getKubeconfig().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cloud.pass.grpc.common.Common.CommonRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloud.pass.grpc.common.Common.CommonRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloud.pass.grpc.common.Common.CommonRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloud.pass.grpc.common.Common.CommonRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloud.pass.grpc.common.Common.CommonRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloud.pass.grpc.common.Common.CommonRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloud.pass.grpc.common.Common.CommonRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloud.pass.grpc.common.Common.CommonRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloud.pass.grpc.common.Common.CommonRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cloud.pass.grpc.common.Common.CommonRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloud.pass.grpc.common.Common.CommonRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloud.pass.grpc.common.Common.CommonRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cloud.pass.grpc.common.Common.CommonRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommonRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommonRequest)
        com.cloud.pass.grpc.common.Common.CommonRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloud.pass.grpc.common.Common.internal_static_CommonRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloud.pass.grpc.common.Common.internal_static_CommonRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloud.pass.grpc.common.Common.CommonRequest.class, com.cloud.pass.grpc.common.Common.CommonRequest.Builder.class);
      }

      // Construct using com.cloud.pass.grpc.common.Common.CommonRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        kubeconfig_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloud.pass.grpc.common.Common.internal_static_CommonRequest_descriptor;
      }

      @java.lang.Override
      public com.cloud.pass.grpc.common.Common.CommonRequest getDefaultInstanceForType() {
        return com.cloud.pass.grpc.common.Common.CommonRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.cloud.pass.grpc.common.Common.CommonRequest build() {
        com.cloud.pass.grpc.common.Common.CommonRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cloud.pass.grpc.common.Common.CommonRequest buildPartial() {
        com.cloud.pass.grpc.common.Common.CommonRequest result = new com.cloud.pass.grpc.common.Common.CommonRequest(this);
        result.kubeconfig_ = kubeconfig_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloud.pass.grpc.common.Common.CommonRequest) {
          return mergeFrom((com.cloud.pass.grpc.common.Common.CommonRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloud.pass.grpc.common.Common.CommonRequest other) {
        if (other == com.cloud.pass.grpc.common.Common.CommonRequest.getDefaultInstance()) return this;
        if (!other.getKubeconfig().isEmpty()) {
          kubeconfig_ = other.kubeconfig_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloud.pass.grpc.common.Common.CommonRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloud.pass.grpc.common.Common.CommonRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object kubeconfig_ = "";
      /**
       * <code>string kubeconfig = 1;</code>
       */
      public java.lang.String getKubeconfig() {
        java.lang.Object ref = kubeconfig_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          kubeconfig_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string kubeconfig = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKubeconfigBytes() {
        java.lang.Object ref = kubeconfig_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kubeconfig_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string kubeconfig = 1;</code>
       */
      public Builder setKubeconfig(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kubeconfig_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string kubeconfig = 1;</code>
       */
      public Builder clearKubeconfig() {
        
        kubeconfig_ = getDefaultInstance().getKubeconfig();
        onChanged();
        return this;
      }
      /**
       * <code>string kubeconfig = 1;</code>
       */
      public Builder setKubeconfigBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        kubeconfig_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommonRequest)
    }

    // @@protoc_insertion_point(class_scope:CommonRequest)
    private static final com.cloud.pass.grpc.common.Common.CommonRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cloud.pass.grpc.common.Common.CommonRequest();
    }

    public static com.cloud.pass.grpc.common.Common.CommonRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommonRequest>
        PARSER = new com.google.protobuf.AbstractParser<CommonRequest>() {
      @java.lang.Override
      public CommonRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommonRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommonRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommonRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cloud.pass.grpc.common.Common.CommonRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CommonResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommonResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string descryption = 2;</code>
     */
    java.lang.String getDescryption();
    /**
     * <code>string descryption = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescryptionBytes();

    /**
     * <code>int32 resultCode = 3;</code>
     */
    int getResultCode();
  }
  /**
   * Protobuf type {@code CommonResponse}
   */
  public  static final class CommonResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommonResponse)
      CommonResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommonResponse.newBuilder() to construct.
    private CommonResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommonResponse() {
      descryption_ = "";
      resultCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommonResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              descryption_ = s;
              break;
            }
            case 24: {

              resultCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloud.pass.grpc.common.Common.internal_static_CommonResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloud.pass.grpc.common.Common.internal_static_CommonResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloud.pass.grpc.common.Common.CommonResponse.class, com.cloud.pass.grpc.common.Common.CommonResponse.Builder.class);
    }

    public static final int DESCRYPTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object descryption_;
    /**
     * <code>string descryption = 2;</code>
     */
    public java.lang.String getDescryption() {
      java.lang.Object ref = descryption_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        descryption_ = s;
        return s;
      }
    }
    /**
     * <code>string descryption = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescryptionBytes() {
      java.lang.Object ref = descryption_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        descryption_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULTCODE_FIELD_NUMBER = 3;
    private int resultCode_;
    /**
     * <code>int32 resultCode = 3;</code>
     */
    public int getResultCode() {
      return resultCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDescryptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, descryption_);
      }
      if (resultCode_ != 0) {
        output.writeInt32(3, resultCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDescryptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, descryption_);
      }
      if (resultCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, resultCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cloud.pass.grpc.common.Common.CommonResponse)) {
        return super.equals(obj);
      }
      com.cloud.pass.grpc.common.Common.CommonResponse other = (com.cloud.pass.grpc.common.Common.CommonResponse) obj;

      boolean result = true;
      result = result && getDescryption()
          .equals(other.getDescryption());
      result = result && (getResultCode()
          == other.getResultCode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DESCRYPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescryption().hashCode();
      hash = (37 * hash) + RESULTCODE_FIELD_NUMBER;
      hash = (53 * hash) + getResultCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cloud.pass.grpc.common.Common.CommonResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloud.pass.grpc.common.Common.CommonResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloud.pass.grpc.common.Common.CommonResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloud.pass.grpc.common.Common.CommonResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloud.pass.grpc.common.Common.CommonResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloud.pass.grpc.common.Common.CommonResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloud.pass.grpc.common.Common.CommonResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloud.pass.grpc.common.Common.CommonResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloud.pass.grpc.common.Common.CommonResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cloud.pass.grpc.common.Common.CommonResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloud.pass.grpc.common.Common.CommonResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloud.pass.grpc.common.Common.CommonResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cloud.pass.grpc.common.Common.CommonResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommonResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommonResponse)
        com.cloud.pass.grpc.common.Common.CommonResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloud.pass.grpc.common.Common.internal_static_CommonResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloud.pass.grpc.common.Common.internal_static_CommonResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloud.pass.grpc.common.Common.CommonResponse.class, com.cloud.pass.grpc.common.Common.CommonResponse.Builder.class);
      }

      // Construct using com.cloud.pass.grpc.common.Common.CommonResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        descryption_ = "";

        resultCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloud.pass.grpc.common.Common.internal_static_CommonResponse_descriptor;
      }

      @java.lang.Override
      public com.cloud.pass.grpc.common.Common.CommonResponse getDefaultInstanceForType() {
        return com.cloud.pass.grpc.common.Common.CommonResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.cloud.pass.grpc.common.Common.CommonResponse build() {
        com.cloud.pass.grpc.common.Common.CommonResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cloud.pass.grpc.common.Common.CommonResponse buildPartial() {
        com.cloud.pass.grpc.common.Common.CommonResponse result = new com.cloud.pass.grpc.common.Common.CommonResponse(this);
        result.descryption_ = descryption_;
        result.resultCode_ = resultCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloud.pass.grpc.common.Common.CommonResponse) {
          return mergeFrom((com.cloud.pass.grpc.common.Common.CommonResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloud.pass.grpc.common.Common.CommonResponse other) {
        if (other == com.cloud.pass.grpc.common.Common.CommonResponse.getDefaultInstance()) return this;
        if (!other.getDescryption().isEmpty()) {
          descryption_ = other.descryption_;
          onChanged();
        }
        if (other.getResultCode() != 0) {
          setResultCode(other.getResultCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloud.pass.grpc.common.Common.CommonResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloud.pass.grpc.common.Common.CommonResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object descryption_ = "";
      /**
       * <code>string descryption = 2;</code>
       */
      public java.lang.String getDescryption() {
        java.lang.Object ref = descryption_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          descryption_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string descryption = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescryptionBytes() {
        java.lang.Object ref = descryption_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          descryption_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string descryption = 2;</code>
       */
      public Builder setDescryption(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        descryption_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string descryption = 2;</code>
       */
      public Builder clearDescryption() {
        
        descryption_ = getDefaultInstance().getDescryption();
        onChanged();
        return this;
      }
      /**
       * <code>string descryption = 2;</code>
       */
      public Builder setDescryptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        descryption_ = value;
        onChanged();
        return this;
      }

      private int resultCode_ ;
      /**
       * <code>int32 resultCode = 3;</code>
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <code>int32 resultCode = 3;</code>
       */
      public Builder setResultCode(int value) {
        
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 resultCode = 3;</code>
       */
      public Builder clearResultCode() {
        
        resultCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommonResponse)
    }

    // @@protoc_insertion_point(class_scope:CommonResponse)
    private static final com.cloud.pass.grpc.common.Common.CommonResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cloud.pass.grpc.common.Common.CommonResponse();
    }

    public static com.cloud.pass.grpc.common.Common.CommonResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommonResponse>
        PARSER = new com.google.protobuf.AbstractParser<CommonResponse>() {
      @java.lang.Override
      public CommonResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommonResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommonResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommonResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cloud.pass.grpc.common.Common.CommonResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommonRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommonRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommonResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\"#\n\rCommonRequest\022\022\n\nkubec" +
      "onfig\030\001 \001(\t\"9\n\016CommonResponse\022\023\n\013descryp" +
      "tion\030\002 \001(\t\022\022\n\nresultCode\030\003 \001(\005B7\n\032com.cl" +
      "oud.pass.grpc.commonZ\031kubectl-cli/common" +
      ";commonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CommonRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommonRequest_descriptor,
        new java.lang.String[] { "Kubeconfig", });
    internal_static_CommonResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CommonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommonResponse_descriptor,
        new java.lang.String[] { "Descryption", "ResultCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
